// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt02ceIjbw8FC-QFKt1RmV1sio0_B45mY',
    appId: '1:719721613814:web:8c00e999de5aa16f129fd7',
    messagingSenderId: '719721613814',
    projectId: 'tasks-2ff84',
    authDomain: 'tasks-2ff84.firebaseapp.com',
    storageBucket: 'tasks-2ff84.appspot.com',
    measurementId: 'G-TES4GQPZXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92m4-QZpU_N9bZkKuu2Zl9eIuqaqupA8',
    appId: '1:719721613814:android:c6ca300b905aca12129fd7',
    messagingSenderId: '719721613814',
    projectId: 'tasks-2ff84',
    storageBucket: 'tasks-2ff84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbnQu00pEZSq0yPvr9K-ZNBj2OcesYV40',
    appId: '1:719721613814:ios:b03c81871916e97a129fd7',
    messagingSenderId: '719721613814',
    projectId: 'tasks-2ff84',
    storageBucket: 'tasks-2ff84.appspot.com',
    iosBundleId: 'com.example.taskes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbnQu00pEZSq0yPvr9K-ZNBj2OcesYV40',
    appId: '1:719721613814:ios:b03c81871916e97a129fd7',
    messagingSenderId: '719721613814',
    projectId: 'tasks-2ff84',
    storageBucket: 'tasks-2ff84.appspot.com',
    iosBundleId: 'com.example.taskes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt02ceIjbw8FC-QFKt1RmV1sio0_B45mY',
    appId: '1:719721613814:web:82f40c5eb1f2eb38129fd7',
    messagingSenderId: '719721613814',
    projectId: 'tasks-2ff84',
    authDomain: 'tasks-2ff84.firebaseapp.com',
    storageBucket: 'tasks-2ff84.appspot.com',
    measurementId: 'G-Z3M6QLD5J1',
  );
}
